version: 2
updates:
  - package-ecosystem: gomod
    directory: /src/auth-service
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /src/bulletin-board-service
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /src/comment-service
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /src/feed-service
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /src/notification-service
    schedule:
      interval: daily