services:
  gateway:
    build:
      context: ./
      dockerfile: ./src/api-gateway/Dockerfile
    command:
      [
        "/app/src/api-gateway/main",
        "-config",
        "/app/config/api-gateway.json"
      ]
    ports:
      - '3000:3000'
    environment:
      - HTTP_SERVER_PORT=3000
    depends_on:
      - auth-service
      - bulletin-board-service
      - feed-service
      - web-service
  web-service:
    build:
      context: ./
      dockerfile: ./src/web-service/Dockerfile
    environment:
      - HTTP_SERVER_PORT=3000
  auth-service:
    build:
      context: ./
      dockerfile: ./src/auth-service/Dockerfile
    environment:
      - HTTP_SERVER_PORT=3000
      - GRPC_SERVER_PORT=50051
      - JWT_PRIVATE_KEY=./key
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
    depends_on:
      postgres:
        condition: service_healthy
  bulletin-board-service:
    build:
      context: ./
      dockerfile: ./src/bulletin-board-service/Dockerfile
    environment:
      - HTTP_SERVER_PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - AUTH_SERVICE_URL_GRPC=auth-service:50051
    depends_on:
      postgres:
        condition: service_healthy
  feed-service:
    build:
      context: ./
      dockerfile: ./src/feed-service/Dockerfile
    environment:
      - HTTP_SERVER_PORT=3000
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/01-create.sql:/docker-entrypoint-initdb.d/01-create.sql
      - ./scripts/02-insert.sql:/docker-entrypoint-initdb.d/02-insert.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bulletinboard:
    driver: bridge
    name: bulletinboard
