apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-service
spec:
  selector:
    matchLabels:
      app: web-service
  replicas: 1
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
        - name: web-service
          image: ghcr.io/flo0807/hsfl-master-ai-cloud-engineering/web-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HTTP_SERVER_PORT
              value: "3000"
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 100m
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: web-deployment
  labels:
    app: web-service
spec:
  scaleTargetRef:
    kind: Deployment
    name: web-deployment
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: web-service
        target:
          type: Utilization
          averageUtilization: 80